// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://www.baidu.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get_id": {
            "get": {
                "description": "获取主键id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "获取主键id",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "服务是否启动正常检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "健康检查接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/account/list": {
            "get": {
                "description": "获取股东数据列表分页 后台用户管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "获取股东数据列表分页",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id 可选参数",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取当页条数",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/account/pwd_login": {
            "post": {
                "description": "账号密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "账号密码登录",
                "parameters": [
                    {
                        "description": "账号密码登录 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.PwdLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/account/register": {
            "post": {
                "description": "股东账号注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "股东账号注册",
                "parameters": [
                    {
                        "description": "股东手机验证码登录 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.RegisterAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/app": {
            "get": {
                "description": "获取app版本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "获取app版本信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ios|android",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/app/down/{type}/{name}": {
            "get": {
                "description": "app下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "app下载链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ios|android",
                        "name": "type",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "apk name",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/app/uploads": {
            "post": {
                "description": "更新app json版本信息,apk暂时存放服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "更新app apk暂时存放服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ios|android",
                        "name": "type",
                        "in": "header"
                    },
                    {
                        "type": "file",
                        "description": "file 上传文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool/create": {
            "post": {
                "description": "创建矿池",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "创建矿池",
                "parameters": [
                    {
                        "description": "创建矿池 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.CreateFilPool"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool/detail": {
            "get": {
                "description": "获取矿池数据详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "获取矿池数据详情",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool/list": {
            "get": {
                "description": "获取矿池数据列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "获取矿池数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id 可选参数",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取当页条数",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool/update": {
            "post": {
                "description": "更新矿池",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "更新矿池",
                "parameters": [
                    {
                        "description": "更新矿池 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.UpadteFilPool"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool_daily/create": {
            "post": {
                "description": "创建每日矿池收益",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "创建每日矿池收益",
                "parameters": [
                    {
                        "description": "创建每日矿池收益 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.CreateFilPoolDailyIncome"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool_daily/detail": {
            "get": {
                "description": "获取每日矿池收益数据详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "获取每日矿池收益数据详情",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool_daily/list": {
            "get": {
                "description": "获取每日矿池收益数据列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "矿池"
                ],
                "summary": "获取每日矿池收益数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id 可选参数",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取当页条数",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool_ratio/create": {
            "post": {
                "description": "批量创建股东矿池比例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东矿池比例"
                ],
                "summary": "批量创建股东矿池比例",
                "parameters": [
                    {
                        "description": "创建股东矿池比例 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.CreateFilPoolRatio"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool_ratio/detail": {
            "get": {
                "description": "根据矿池id获取股东矿池列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东矿池比例"
                ],
                "summary": "根据矿池id获取股东矿池列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/fil_pool_ratio/list": {
            "get": {
                "description": "获取股东矿池比例数据列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东矿池比例"
                ],
                "summary": "获取股东矿池比例数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id 可选参数",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取当页条数",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/news/daily_news": {
            "get": {
                "description": "24小说交易排行数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯模块"
                ],
                "summary": "24小说交易排行数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/news/futures_stat": {
            "get": {
                "description": "24小时爆仓统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯模块"
                ],
                "summary": "24小时爆仓统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/news/futuresmarket_bitcoin": {
            "get": {
                "description": "24小时多空比",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯模块"
                ],
                "summary": "24小时多空比",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/news/futuresmarket_exchange": {
            "get": {
                "description": "交易所期货数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯模块"
                ],
                "summary": "交易所期货数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/news/web_exchange": {
            "get": {
                "description": "获取交易所排行数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资讯模块"
                ],
                "summary": "获取交易所排行数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/detail": {
            "get": {
                "description": "获取股东信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "获取股东信息",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/income_list": {
            "get": {
                "description": "获取股东每日收益数据列表分页 后台用户管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "获取股东每日收益数据列表分页",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id 可选参数",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取当页条数",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/info": {
            "get": {
                "description": "获取收益统计数据 app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "获取收益统计数据",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/list": {
            "get": {
                "description": "矿池分配股东时,需要有股东列表去选择",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "获取股东数据列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/set_enable": {
            "post": {
                "description": "是否禁用用户 后台用户管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "是否禁用用户",
                "parameters": [
                    {
                        "description": "是否禁用用户 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.SetEnable"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/set_pwd": {
            "post": {
                "description": "股东设置提现密码 需要提供登录密码 后面可迭代加上短信验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "股东设置提现密码",
                "parameters": [
                    {
                        "description": "股东设置提现密码 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.SetWithdrawalPwd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/subordinate_list": {
            "get": {
                "description": "获取股东下级列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "获取股东下级列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/shareholder/update_percent": {
            "post": {
                "description": "股东更新再分配占比例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "股东"
                ],
                "summary": "股东更新再分配占比例",
                "parameters": [
                    {
                        "description": "股东更新再分配占比例 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.UpdatePercentShareholderID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/sms/send": {
            "post": {
                "description": "发送短信验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "发送短信验证码",
                "parameters": [
                    {
                        "description": "发送短信验证码 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.SmsSend"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/withdrawal/account_list": {
            "get": {
                "description": "获取股东提现申请列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提现"
                ],
                "summary": "获取股东提现申请列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/withdrawal/application": {
            "post": {
                "description": "创建提现申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提现"
                ],
                "summary": "创建提现申请",
                "parameters": [
                    {
                        "description": "创建提现申请 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.ApplicationWithdrawal"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/withdrawal/detail": {
            "get": {
                "description": "获取提现申请详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提现"
                ],
                "summary": "获取提现申请详情",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/withdrawal/list": {
            "get": {
                "description": "获取提现申请数据列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提现"
                ],
                "summary": "获取提现申请数据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id 可选参数",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "获取当页条数",
                        "name": "num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/withdrawal/pass": {
            "post": {
                "description": "后台通过提现申请 1、申请状态改为通过 2、需要扣除对应股东余额",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提现"
                ],
                "summary": "后台通过提现申请",
                "parameters": [
                    {
                        "description": "后台通过提现申请 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.Detail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/v1/withdrawal/reject": {
            "post": {
                "description": "后台驳回提现申请 1、申请状态改为驳回 2、需要添加驳回原因",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提现"
                ],
                "summary": "后台驳回提现申请",
                "parameters": [
                    {
                        "description": "后台驳回提现申请 需要的参数",
                        "name": "param",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.WithdrawalReject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.ApplicationWithdrawal": {
            "type": "object",
            "required": [
                "amount",
                "hash",
                "shareholder_id",
                "withdrawal_pwd"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "content": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "shareholder_id": {
                    "type": "string"
                },
                "with_log": {
                    "type": "string"
                },
                "withdrawal_pwd": {
                    "type": "string"
                }
            }
        },
        "request.CreateFilPool": {
            "type": "object",
            "required": [
                "effective_computing_power",
                "miner",
                "miner_available_balance",
                "miner_balance",
                "name",
                "node_id",
                "original_computing_power",
                "sector_size"
            ],
            "properties": {
                "effective_computing_power": {
                    "description": "\"有效算力\"",
                    "type": "string"
                },
                "miner": {
                    "description": "\"矿工\"",
                    "type": "string"
                },
                "miner_available_balance": {
                    "description": "\"可用余额\"",
                    "type": "number"
                },
                "miner_balance": {
                    "description": "\"账户余额\"",
                    "type": "number"
                },
                "name": {
                    "description": "\"矿池名称\"",
                    "type": "string"
                },
                "node_id": {
                    "description": "\"节点id\"",
                    "type": "string"
                },
                "original_computing_power": {
                    "description": "\"原值算力\"",
                    "type": "string"
                },
                "sector_size": {
                    "description": "\"扇区大小\"",
                    "type": "number"
                }
            }
        },
        "request.CreateFilPoolDailyIncome": {
            "type": "object",
            "required": [
                "assigned_val",
                "fil_pool_id",
                "freed",
                "last_time_val",
                "today_val"
            ],
            "properties": {
                "assigned_val": {
                    "description": "分配值",
                    "type": "number"
                },
                "fil_pool_id": {
                    "description": "矿池id",
                    "type": "string"
                },
                "freed": {
                    "description": "有效算力",
                    "type": "number"
                },
                "last_time_val": {
                    "description": "上次值",
                    "type": "number"
                },
                "today_val": {
                    "description": "本日值",
                    "type": "number"
                }
            }
        },
        "request.CreateFilPoolRatio": {
            "type": "object",
            "required": [
                "fil_pool_id",
                "list"
            ],
            "properties": {
                "fil_pool_id": {
                    "type": "string"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.ShareholerShareList"
                    }
                }
            }
        },
        "request.Detail": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "request.PwdLogin": {
            "type": "object",
            "required": [
                "mobile",
                "pwd"
            ],
            "properties": {
                "mobile": {
                    "type": "string"
                },
                "pwd": {
                    "type": "string"
                }
            }
        },
        "request.RegisterAccount": {
            "type": "object",
            "required": [
                "is_enable",
                "mobile",
                "pwd",
                "sms_code"
            ],
            "properties": {
                "is_enable": {
                    "description": "是否开启",
                    "type": "boolean"
                },
                "mobile": {
                    "description": "手机号码",
                    "type": "string"
                },
                "pwd": {
                    "description": "密码",
                    "type": "string"
                },
                "recommend_code": {
                    "description": "推荐码 没有，可不填",
                    "type": "string"
                },
                "sms_code": {
                    "description": "短信验证码",
                    "type": "string"
                }
            }
        },
        "request.SetEnable": {
            "type": "object",
            "required": [
                "id",
                "is_enable",
                "shareholder_id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_enable": {
                    "type": "boolean"
                },
                "shareholder_id": {
                    "type": "string"
                }
            }
        },
        "request.SetWithdrawalPwd": {
            "type": "object",
            "required": [
                "login_pwd",
                "shareholder_id",
                "withdrawal_pwd"
            ],
            "properties": {
                "login_pwd": {
                    "type": "string"
                },
                "shareholder_id": {
                    "type": "string"
                },
                "withdrawal_pwd": {
                    "type": "string"
                }
            }
        },
        "request.ShareholerShareList": {
            "type": "object",
            "required": [
                "proportion_of_shares",
                "shareholder_id"
            ],
            "properties": {
                "proportion_of_shares": {
                    "type": "integer"
                },
                "shareholder_id": {
                    "type": "string"
                }
            }
        },
        "request.SmsSend": {
            "type": "object",
            "required": [
                "mobile"
            ],
            "properties": {
                "mobile": {
                    "type": "string"
                }
            }
        },
        "request.UpadteFilPool": {
            "type": "object",
            "required": [
                "effective_computing_power",
                "id",
                "miner",
                "miner_available_balance",
                "miner_balance",
                "name",
                "node_id",
                "original_computing_power",
                "sector_size"
            ],
            "properties": {
                "effective_computing_power": {
                    "description": "\"有效算力\"",
                    "type": "string"
                },
                "id": {
                    "description": "\"矿池名称\"",
                    "type": "string"
                },
                "miner": {
                    "description": "\"矿工\"",
                    "type": "string"
                },
                "miner_available_balance": {
                    "description": "\"可用余额\"",
                    "type": "number"
                },
                "miner_balance": {
                    "description": "\"账户余额\"",
                    "type": "number"
                },
                "name": {
                    "description": "\"矿池名称\"",
                    "type": "string"
                },
                "node_id": {
                    "description": "\"节点id\"",
                    "type": "string"
                },
                "original_computing_power": {
                    "description": "\"原值算力\"",
                    "type": "string"
                },
                "sector_size": {
                    "description": "\"扇区大小\"",
                    "type": "number"
                }
            }
        },
        "request.UpdatePercentShareholderID": {
            "type": "object",
            "required": [
                "shareholder_id"
            ],
            "properties": {
                "percent_five_shareholder_id": {
                    "type": "string"
                },
                "percent_three_shareholder_id": {
                    "type": "string"
                },
                "shareholder_id": {
                    "type": "string"
                }
            }
        },
        "request.WithdrawalReject": {
            "type": "object",
            "required": [
                "content",
                "id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "response.Resp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "2.0",
	Host:        "192.168.1.163:7001",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "swagger 接口文档",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
